# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d689278092dce7da19075b69542a50f344d6ea41d482b4a65fd50c08cbe05366c63e375b3dfe7d9a14918537b6d46a6a3c98907456d684e374deb734726305c

test:
  secret_key_base: 40a808ca1bf358c7baa631aab04a36bfc02694d8c8afa6912b5eab86b0cd4828eac5cc7c8ac4ef8c6992346f4bcfdad309e32d22f9f29d7960a49a79c135431d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
